### ISSUE TITLE
[DOCS]: Lack of a README file.

### ISSUE THREAD

**Issue by debarshee2004** [bishakhne0gi/Spring-Crud#1]
## Issue Summary

I noticed that the repository Spring-Crud currently lacks a `README.md` file. A `README` file is crucial for providing essential information about the project, its purpose, and how to get started with it. Having a well-documented `README.md` file is not only helpful for contributors but also for users who come across the repository.

## Solution

Writing a proper `README.md` file which would include:
- Information about the Project
- Basic understanding on how it works
- How to setup the project

I @debarshee2004 would like to take the responsibility of this ISSUE.
Thank you.

**Comment by bishakhne0gi** [comment]
Yes sure, I shall assign you the issue. Happy coding!

**Comment by debarshee2004** [comment]
Thank you @bishakhne0gi  , Happy coding.
