### ISSUE TITLE
[FEAT]: Making the Landing page more better

### ISSUE THREAD

**Issue by debarshee2004** [bishakhne0gi/Spring-Crud#12]
**Description**: The current landing page only has a text and a button
*Current*
![scwa-home](https://github.com/bishakhne0gi/Spring-Crud/assets/129538241/5b2c1867-f195-4edb-9b79-5f5112ec9449)
 
**Solution**: By adding some documentation, explanation, contributors section, footer and some feature it can pop up.

**Comment by bishakhne0gi** [comment]
Na na i want to keep the way it is!!
@debarshee2004

**Comment by debarshee2004** [comment]
Ok sir.
