### ISSUE TITLE
frontend feature: Tasks assigned to employees

### ISSUE THREAD

**Issue by itsyourap** [bishakhne0gi/Spring-Crud#13]
This application does have APIs for CRUD operations of Tasks and assigning Tasks to employees and removing them from tasks but this application lacks the frontend capabilities to do so.

I would like to work on this issue and create a frontend component for adding and managing tasks.

**Comment by itsyourap** [comment]
@bishakhne0gi Can you please assign this to me?

**Comment by bishakhne0gi** [comment]
Yes that's needed very much @itsyourap
